swagger: '2.0'
info:
  title: "Human Services Link"
  description: "This is a Human Services Data Specification (HSDS) website, and API that runs entirely on Github, leveraging Jekyll and Github pages. This is a developer API for getting at the data made available via this poject."
  termsOfService: "https://openreferral.org/documentation/"
  contact:
    name: Open Referral
    url: https://openreferral.org/
    email: info@openreferral.org
  license:
    name: Open Data Commons Public Domain
    url: http://opendatacommons.org/licenses/pddl/
  version: v1.1
host: adopta-agency.github.io
basePath: /human-services-link/apis
schemes:
- https
produces:
- application/json
paths:
  /locations/:
    get:
      summary: Get Locations
      description: Get Locations
      operationId: listLocations
      parameters:
        - in: query
          type: number
          name: page
          description: The particular page of results.
        - in: query
          type: number
          name: per_page
          description: Amount of locations to return per page, up to 100.
      responses:
        '200':
          description: Location Response
          schema:
            type: array
            items:
              $ref: "#/definitions/location"
      tags:
      - Locations
definitions:
  location:
    properties:
      name:
        description: 'The name of the location.'
        type: string
      description:
        description: 'A description of this location.'
        type: string
      physical_address:
        description: 'An array of physical addresses'
        schema:
          type: array
          items:
            $ref: '#/definitions/physical_address'
      services:
        description: 'An array of services'
        schema:
          type: array
          items:
            $ref: '#/definitions/service'
  physical_address:
    properties:
      address_1:
        description: 'The first line of the address.'
        type: string
      city:
        description: 'The city in which the address is located.'
        type: string
      state_province:
        description: 'The state or province in which the address is located.'
        type: string
    required:
      - address_1
      - city
      - state_province
  regular_schedule:
    properties:
      weekday:
        description: 'The day of the week that this entry relates to.'
        type: integer
      opens_at:
        description: 'The time when a service or location opens. This should use HH:MM format and should include timezone information, either adding the suffix ‘Z’ when the date is in UTC, or including an offset from UTC (e.g. 09:00-05:00 for 9am East Coast Time.'
        type: string
      closes_at:
        description: 'The time when a service or location opens. This should use HH:MM format and should include timezone information, either adding the suffix ‘Z’ when the date is in UTC, or including an offset from UTC (e.g. 09:00-05:00 for 9am East Coast Time.'
        type: string
    required:
      - weekday
  service:
    properties:
      name:
        description: 'The official or public name of the service.'
        type: string
      description:
        description: 'A description of the service.'
        type: string
      application_process:
        description: 'The steps needed to access the service.'
        type: string
      taxonomy_ids:
        description: 'A comma separated list of names from the taxonomy table. This field is deprecated in favour of using the service_taxonomy table.'
        type: string
    required:
      - name
  taxonomy:
    properties:
      name:
        description: 'The name of this taxonomy term or category.'
        type: string
    required:
      - name
