- name: Open Referral
  title: Open Referral
  license:
  - url: http://opendatacommons.org/licenses/pddl/
    name: Open Data Commons Public Domain
    version: '1.0'
    id: odc-pddl
  resources:
  - name: organization
    path: organization.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        type: string
      - name: name
        type: string
      - name: alternate_name
        type: string
      - name: description
        type: string
        format: ''
      - name: email
        type: string
      - name: url
        type: string
      - name: tax_status
        type: string
      - name: tax_id
        type: string
      - name: year_incorporated
        type: date
        format: yyyy
      - name: legal_status
        type: string
      primaryKey: id
  - name: program
    path: program.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: organization_id
        description: ''
        type: string
      - name: name
        description: ''
        type: string
      - name: alternate_name
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: organization_id
        reference:
          resource: organization.csv
          fields: id
  - name: service
    path: service.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: organization_id
        description: ''
        type: string
      - name: program_id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: name
        description: ''
        type: string
      - name: alternate_name
        description: ''
        type: string
      - name: url
        description: ''
        type: string
      - name: email
        description: ''
        type: string
      - name: status
        description: ''
        type: string
        values:
        - active
        - inactive
        - defunct
        - temporarily closed
      - name: application_process
        description: ''
        type: string
      - name: wait_time
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: organization_id
        reference:
          resource: organization.csv
          fields: id
      - fields: program_id
        reference:
          resource: program.csv
          fields: id
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
  - name: service_at_location
    path: service_at_location.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: url
        description: ''
        type: string
      - name: email
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
  - name: location
    path: program.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: organization_id
        description: ''
        type: string
      - name: name
        description: ''
        type: string
      - name: alternate_name
        description: ''
        type: string
      - name: transportation
        description: ''
        type: string
      - name: latitude
        description: ''
        type: float
      - name: longitude
        description: ''
        type: float
      primaryKey: id
      foreignKeys:
      - fields: organization_id
        reference:
          resource: organization.csv
          fields: id
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: phone
    path: phone.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: organization_id
        description: ''
        type: string
      - name: contact_id
        description: ''
        type: string
      - name: number
        description: ''
        type: string
      - name: extension
        description: ''
        type: number
      - name: type
        description: ''
        type: string
      - name: department
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: organization_id
        reference:
          resource: organization.csv
          fields: id
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
      - fields: contact_id
        reference:
          resource: contact.csv
          fields: id
  - name: contact
    path: contact.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: organization_id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: name
        description: ''
        type: string
      - name: title
        description: ''
        type: string
      - name: department
        description: ''
        type: string
      - name: email
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: organization_id
        reference:
          resource: organization.csv
          fields: id
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: physical_address
    path: address.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: attention
        description: ''
        type: string
      - name: address_1
        description: ''
        type: string
      - name: address_2
        description: ''
        type: string
      - name: address_3
        description: ''
        type: string
      - name: address_4
        description: ''
        type: string
      - name: city
        description: ''
        type: string
      - name: state_province
        description: ''
        type: string
      - name: postal_code
        description: ''
        type: string
      - name: country
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
  - name: postal_address
    path: address.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: attention
        description: ''
        type: string
      - name: address_1
        description: ''
        type: string
      - name: address_2
        description: ''
        type: string
      - name: address_3
        description: ''
        type: string
      - name: address_4
        description: ''
        type: string
      - name: city
        description: ''
        type: string
      - name: state_province
        description: ''
        type: string
      - name: postal_code
        description: ''
        type: string
      - name: country
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
  - name: regular_schedule
    path: regular_schedule.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: weekday
        description: ''
        type: integer
      - name: opens_at
        description: ''
        type: time
      - name: closes_at
        description: ''
        type: time
      primaryKey: id
      foreignKeys:
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: holiday_schedule
    path: holiday_schedule.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: closed
        description: ''
        type: boolean
      - name: opens_at
        description: ''
        type: time
      - name: closes_at
        description: ''
        type: time
      - name: start_date
        description: ''
        type: date
      - name: end_date
        description: ''
        type: date
      primaryKey: id
      foreignKeys:
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: funding
    path: funding.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: organization_id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: source
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
      - fields: organization_id
        reference:
          resource: organization.csv
          fields: id
  - name: eligibility
    path: eligibility.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: eligibility
        description: ''
        type: string
        values:
        - adult
        - child
        - teen
        - family
        - female
        - male
        - Transgender
        - Transgender - M to F
        - Transgender - F to M
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: service_area
    path: service_area.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: service_area
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: required_document
    path: required_document.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: document
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: fee
    path: fee.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: fee
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: payment_accepted
    path: payment_accepted.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: payment
        description: ''
        type: string
        values:
        - cash
        - check
        - money order
        - credit card
        - medicare
        - SNAP
        - WIC
        - EBT
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: intepretation_services
    path: interpretation_services.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: language
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: language
    path: language.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: service_id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: language
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
      - fields: location_id
        reference:
          resource: location.csv
          fields: id
  - name: accessibility_for_disabilities
    path: accessibility_for_disabilities.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: location_id
        description: ''
        type: string
      - name: accessibility
        description: ''
        type: string
        values:
        - cd
        - deaf_interpreter
        - disabled_parking
        - elevator
        - ramp
        - restroom
        - tape_braille
        - tty
        - wheelchair
        - wheelchair_van
      primaryKey: id
      foreignKeys:
      - fields: service_id
        reference:
          resource: service.csv
          fields: id
  - name: metadata
    path: metadata.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: resource_id
        description: ''
        type: string
      - name: last_action_date
        description: ''
        type: string
      - name: last_action_type
        description: ''
        type: string
      - name: field_name
        description: ''
        type: string
      - name: previous_value
        description: ''
        type: string
      - name: replacement_value
        description: ''
        type: string
      - name: updated_by
        description: ''
        type: string
      primaryKey: id
      foreignKeys:
      - fields: resource_id
        reference:
          resource: location.csv
          fields: id
      - fields: resource_id
        reference:
          resource: service.csv
          fields: id
      - fields: resource_id
        reference:
          resource: organization.csv
          fields: id
      - fields: resource_id
        reference:
          resource: program.csv
          fields: id
      - fields: resource_id
        reference:
          resource: address.csv
          fields: id
      - fields: resource_id
        reference:
          resource: contact.csv
          fields: id
      - fields: resource_id
        reference:
          resource: holiday_schedules.csv
          fields: id
      - fields: resource_id
        reference:
          resource: regular_schedules.csv
          fields: id
      - fields: resource_id
        reference:
          resource: phone.csv
          fields: id
  - name: meta_table_description
    path: meta_table_description.csv
    format: csv
    mediatype: text/csv
    schema:
      fields:
      - name: id
        description: ''
        type: string
      - name: name
        description: ''
        type: string
      - name: language
        description: ''
        type: string
      - name: character_set
        description: ''
        type: string
      primaryKey: id
